### ISSUE TITLE
Controllare DB

### ISSUE THREAD

**Issue by wuxyel123** [EgonGalvani/TecWeb#1]
Bisogna controllare se tutti i campi/relazioni vanno bene o se c'è qualcosa da modificare.
In 'Ristorante' gli orari di apertura/chiusura si potrebbero mettere in un'altra tabella perché forse è più pulito che avere il campo "Giorno di chiusura". Tipo una roba del genere:
```
CREATE TABLE "orari" (
     "ID" integer NOT NULL PRIMARY KEY,
     "ID_Ristorante" integer NOT NULL FOREIGN KEY REFERENCES "ristorante.ID",
     "giorno" varchar NOT NULL,
     "apertura" time,
     "chiusura" time
)
```

**Comment by EgonGalvani** [comment]
Per la password direi che sarebbe opportuno salvare un hash, al posto della psw in chiaro. Usando ad esempio una sha256 come funzione di hash, sono 256 bit, e quindi salvandola in esadecimale va bene la varchar64. 

Poi per ristoratore, utente e admin, secondo me sarebbe meglio fare 3 tabelle diverse. Alla fine alcuni campi in alcune servono e in altre no. 
Piu' che altro, 
dell'utente servono: nome, cognome, email, password, foto 
del ristoratore potremo chiedere qualcosa in più, quindi: nome, cognome, email, indirizzo, codice fiscale, p.iva e foto.

**Comment by EgonGalvani** [comment]
Poi per la foto dobbiamo chiarire se fare un attributo per gli utenti e una tabella dedicata per i ristoranti.

**Comment by wuxyel123** [comment]
Il salvataggio in hash era già considerato, l'utente abbiamo deciso di raggrupparlo in uno io e cocco e riguardo alla foto va rinominata sicuramente.

**Comment by EgonGalvani** [comment]
Per l'hash ok perfetto, l'ho scritto tanto per essere sicuro. 

Per la foto, appunto, dato che sicuramente va rinominata, non penso sia necessario nel database collegare la tabella utente con quella foto. E si potrebbe fare un'unica tabella (al posto di foto e corrispondenze), in cui metti id ristorante e path della foto. 

Per la decisione di raggruppare tutto in "utente", se siete sicuri che vada bene, ok.

**Comment by wuxyel123** [comment]
Risalire alla foto di qualcuno perché la rinomini con la sua mail è sbagliato, quella la lascerei così. L'utente avrebbe senso anche dividerlo ma direi che ne parliamo domani.

**Comment by EgonGalvani** [comment]
Nella tabella categoria, metterei come chiave primaria un id, e come altro campo solamente il nome. 
La descrizione non penso serva, dato che il nome sara' qualcosa tipo: pizzeria, cinese e via dicendo.
