### ISSUE TITLE
Popolamento Database

### ISSUE THREAD

**Issue by wuxyel123** [EgonGalvani/TecWeb#16]
**Tabelle riempite:**
-Utenti
**Tabelle da riempire:**
-Categoria
-Corrispondenza
-Foto
-MiPiace
-Recensione
-Ristorante

**Comment by EgonGalvani** [comment]
**Tabelle riempite:**
-Utenti
-Categoria
-Ristorante
**Tabelle da riempire:**
-Corrispondenza
-Foto
-MiPiace
-Recensione
