### ISSUE TITLE
Linee guida controlli accessibilità

### ISSUE THREAD

**Issue by EgonGalvani** [EgonGalvani/TecWeb#17]
Elenco delle cose da controllare per un adeguato livello di accessibilità:

**Comment by Alberto1598** [comment]
- Separazione struttura presentazione
- controllare tag xml:lang e abbr
- controllare alt nelle immagini
- validare codice
- controllare i tabindex
- evitare link circolari
- controllare i meta tag, tag title 
- verificare contrasti colori e fare prove disabilita (soprattutto piu avanti) 
- colori link e no sottolineatura parole
- sistemare breadcrumb

**Comment by EgonGalvani** [comment]
- Link visitati e non visitati devono avere due colori diversi

**Comment by Alberto1598** [comment]
Validano in xhtml 1.1 strict :   
- Chi siamo
- dettaglio ristorante
- index
- login
- regolamento
- ultimi ristoranti
