### ISSUE TITLE
Casi d'uso degli utenti

### ISSUE THREAD

**Issue by EgonGalvani** [EgonGalvani/TecWeb#2]
Per essere sicuri, riassumo qui i casi d'uso dei vari utenti. 

Un utente generico (non loggato), può: 
  - eseguire ricerche 
  - visualizzare i dettagli dei ristoranti 
  - vedere le recensioni lasciate dagli altri utenti 
  - visualizzare pagine statiche (come: chi siamo e roba del genere) 

Un utente loggato "normale" può: 
   - fare tutto ciò che può fare un utente generico 
   - inserire recensioni 
   - visualizzare/modificare il proprio profilo 
   - accedere alla pagina "Le mie recensioni"

Un utente loggato "ristoratore" può: 
   - fare tutto ciò che può fare un utente generico 
   - richiedere di inserire dei ristoranti 
   - visualizzare la pagina "I miei ristoranti" 
   - visualizzare/modificare il proprio profilo 

Un utente loggato "admin" può: 
   - fare tutto ciò che può fare un utente generico 
   - eliminare le recensioni di utenti 
   - accedere ad una pagina per approvare richieste di inserimento di ristoranti

**Comment by EgonGalvani** [comment]
Io proporrei di inserire all'utente generico anche la possibilità di: 
  - visualizzare una pagina "Ultime recensioni lasciate"
  - visualizzare una pagina "Ultimi ristoranti inseriti"

**Comment by EgonGalvani** [comment]
Poi pensandoci, l'unica cosa che lascerei modificare a utente "normale" e "ristoratore" del proprio profilo è l'immagine

**Comment by Alberto1598** [comment]
Cioè non lasceresti modificare username, e-mail o altre robe ma solo la foto?

**Comment by Alberto1598** [comment]
Cioè nel senso semplificherebbe abbastanza le cose e sono d'accordo. Io consentirei di modificare username e foto al massimo

**Comment by EgonGalvani** [comment]
Sisi anche secondo me. 
L'unico dubbio è che forse essendo un sito di recensioni è meglio tenere Nome e Cognome al posto di inserire anche un username (tanto per semplicità anche). 
Attualmente nel database non mi sembra ci sia l'username, poi casomai decidiamo se metterlo o no.

**Comment by Alberto1598** [comment]
Si sono d'accordo anche sul togliere l'username nel caso in cui aumenti la complessità per nulla e quindi lasciare solamente la foto da modificare. Per quanto riguarda l'utente, sono molto perplesso onestamente: valutiamo strada facendo se sia meglio separarli o no. Perché magari le query potrebbero risultare più complicate, ma anche occupare memoria con 3 tabelle semi identiche non mi sembra bellissimo.

**Comment by EgonGalvani** [comment]
Ok perfetto, 
per l'username siamo d'accordo. 
Per le tabelle ne parliamo domani e vediamo come fare.

**Comment by Alberto1598** [comment]
La terza possibilità potrebbe essere di avere una tabella utente con tutti i campi in comune più tre chiavi esterne a "utente standard", "admin", "ristoratore" con i rispettivi campi specializzati. Mi sembra il miglior compromesso

**Comment by EgonGalvani** [comment]
Altre funzionalita': 
- (utente loggato "normale" ) mettere like alle recensioni  

Consideriamo di aver salvato l'id dell'utente in $_SESSION, 
le query da avere sono le seguenti: 
- Ricerca: 
  1. (per nome) selezionare tutti i campi dei ristoranti con nome simile a NOME
  2. (per localita') selezionare tutti i campi dei ristoranti con localita' uguale a LOCALITA' 
- Dettagli ristorante: 
  3. selezionare tutti  campi del ristorante con id == ID
- Vedere recensioni lasciate dagli altri utenti: 
  4. Di ogni recensione abbiamo bisogno di: nome, cognome, id e foto dell'utente, stelle, titolo, data, oggetto e descrizione della recensione, numero di like alla recensione e id della recensione ordinate in base a data di inserimento (e di queste ottenere le prime 5 che partono da 5*(page-1) 
  5. Con l'id della recensione, vediamo se l'utente attuale ha messo like 
- 6. Query di inserimento recensione 
- 7. Selezione tutte le informazioni rigaurdanti un utente con id == ID
- 8. Modificare l'immagine di profilo: modifica del path 
- 9. Modificare p.iva
- 10. Modifica password 
- 11. Ottenere tutte le recensioni con ID_Utente == id, e per ogni recensione id e nome ristorante (e di queste ottenere le prime 5 che partono da 5*(page-1)  ) 
- 12. Inserimento ristorante 
- 13. Selezione di tutti i mei ristoranti (ID_Proprietario == id) e la prima foto del ristorante
  ( e di queste ottenere i primi 5 che partono da 5*(page-1) ) 
- 14. Eliminazione recensione tramite id 
- 15. Selezione dei ristoranti non ancora approvati 
- 16. Modificare lo stato di approvazione di un ristorante (false -> true) 
- 17. Visualizzare ultime recensioni lasciate  (e di queste ottenere le prime 5 che partono da 5*(page-1)  ) 
- 18. Visualizzare ultimi ristoranti inseriti (e approvati)  (e di queste ottenere le prime 5 che partono da 5*(page-1)  )

**Comment by wuxyel123** [comment]
https://docs.google.com/document/d/1F1OwNyQsdMW-dE27ETmjTwNzs7-5dRrjFvW6sYm-5Fg/edit?usp=sharing

**Comment by Alberto1598** [comment]
3.SELECT *
FROM ristorante
WHERE ID="%$ID%"

4. SELECT Nome, Cognome, foto.ID, foto.path, recensione.ID, Data, Stelle, Oggetto, Descrizione,COUNT(*) AS numLike
FROM utente, foto, recensione, like
WHERE ID_Utente=utente.ID AND ID_Foto= foto.ID AND recensione.ID=ID_Recensione AND utente.ID=like.ID_Utente
ORDER BY Data DESC
GROUP BY Nome, Cognome, foto.ID, foto.path, recensione.ID, Data, Stelle, Oggetto, Descrizione

Avrei provato a fare le query 3 e 4. Non ho permessi per inserire nel documento pertanto le metto qui. Non assicuro che siano giuste.

**Comment by matteo-munari** [comment]
Le query sono giuste secondo me, l'unica cosa è vedere se serve ottenere foto.ID con la select, perché alla fine interessa solo il path. Un' altra cosa, non mi ricordo, order by e group by si possono mettere come si vuole?

**Comment by Alberto1598** [comment]
Si hai ragione: group by va sempre prima di order by.

**Comment by Alberto1598** [comment]
Fatte query dalla 4 alla 11. La correttezza non e' stata dimostrata.
