### ISSUE TITLE
Colori sito

### ISSUE THREAD

**Issue by wuxyel123** [EgonGalvani/TecWeb#39]
#f29411  #ff8800

**Comment by EgonGalvani** [comment]
https://www.materialpalette.com/indigo/blue

**Comment by EgonGalvani** [comment]
Primo piano:#FFFFFF  Sfondo:#303F9F

Il rapporto di contrasto di luminosità è: 9,0:1

Testo - Superato al livello AA

Testo - Superato al livello AAA

Testo grande - Superato al livello AA

Testo grande - Superato al livello AAA

SC 1.4.3 Contrasto (Minimo): La rappresentazione grafica del testo e delle immagini contenenti testo ha un rapporto di contrasto di luminosità minimo pari a 4.5:1, ad esclusione di: (Livello AA) testo a caratteri larghi e immagini di testo a caratteri larghi hanno un rapporto di contrasto di luminosità minimo pari a 3:1;

SC 1.4.6 Contrasto (Esteso): La rappresentazione grafica del testo e delle immagini contenenti testo ha un rapporto di contrasto di luminosità minimo pari a 7:1, ad esclusione di: (Livello AAA) testo a caratteri larghi e immagini di testo a caratteri larghi hanno un rapporto di contrasto di luminosità minimo pari a 4.5:1

Note: 1. Testo o immagini di testo parte di un componente inattivo di una interfaccia utente, oppure puramente decorativi, o che sono testo secondario in una immagine, o che non sono visibili, non hanno un rapporto di contrasto di luminosità minimo richiesto. 2. Testo che è parte di un logo o di un marchio non ha un rapporto di contrasto di luminosità minimo richiesto.

**Comment by EgonGalvani** [comment]
Usando questi colori ottengo un buon punteggio
Questo è il tool da usare per il contrasto: https://www.webaccessibile.org/articoli/contrast-analyser-versione-22/
