### ISSUE TITLE
Elenco pagine sito

### ISSUE THREAD

**Issue by EgonGalvani** [EgonGalvani/TecWeb#4]
Elenco pagine sito: 
- Home (con ricerca) 
- Ultimi ristoranti inseriti 
- Ultime recensioni lasciate 
- Risultati ricerca
- Dettagli ristorante 
- Profilo 
- I miei ristoranti 
- Le mie recensioni 
- Pannello Amministratore 

Pagine statiche: 
- Chi siamo (presentazione) 
- Regolamento 
- FAQ

Se avete qualche proposta aggiungete

**Comment by Alberto1598** [comment]
Ma quindi nella home apparirebbe solo il menù con la barra di ricerca?

**Comment by EgonGalvani** [comment]
Io metterei la barra di ricerca e sotto delle "anteprime" delle pagine "ultimi ristoranti aggiunti" e "ultime recensioni lasciate"

**Comment by matteo-munari** [comment]
O anche i meglio recensiti ad esempio, come suggerimento di ricerca

**Comment by EgonGalvani** [comment]
Si bell'idea
