### ISSUE TITLE
situazione validazione pagine html

### ISSUE THREAD

**Issue by Alberto1598** [EgonGalvani/TecWeb#40]
Validano in xhtml 1.1 strict sul validatore w3c :   
- Chi siamo
- dettaglio ristorante
- profilo
- index
- login
- regolamento
- ultimi ristoranti
- 404

Validano in html5 (da verificare grado di accessibilità e l'xhtml5 su total validator):
- Le mie recensioni (con un warning sul javascript )
- casuale ( con un warning sul javascript)
- FAQ ( con un warning sul javascript, mettendo lang al posto di xml:lang)
- ins_rist ( con un warning sul javascript, mettendo lang al posto di xml:lang)
- base ( con un warning sul javascript)

Pagine da ricontrollare:
- Registrazione

**Comment by EgonGalvani** [comment]
[x] rimosso il placeholder nella pagina "casuale.html"
